name: C/C++ CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-18.04

    steps:
      - uses: actions/checkout@v1
        with:
          submodules: true
      - name: Install bats
        run: |
          apt-get update -qq
          apt-get install -qq bats
      - run: make
      - run: bats --tap test
